### ISSUE TITLE
Problem creating new hbench server

### ISSUE THREAD

**Issue by barelyknown** [corydolphin/herokubench#1]
I'm seeing the following error when creating an hbench server. I didn't look the cause.

```
Seans-MacBook-Pro:hbench seandevine$ hbench create ff-hbench
/Users/seandevine/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/heroku-2.41.0/lib/heroku/command/base.rb:205: warning: conflicting chdir during another chdir block
Created your personal benchserver: ff-hbench
Initializing repository, done.

-----> Fetching custom git buildpack... done
-----> ApacheBuildpack app detected
-----> Extracting Apache httpd

gzip: stdin: unexpected end of file
tar: Child returned status 1
tar: Exiting with failure status due to previous errors
-----> Updating path
-----> Discovering process types
       Procfile declares types -> (none)

-----> Compressing... done, 2K
-----> Launching... done, v4
       http://ff-hbench.herokuapp.com/ deployed to Heroku
```

**Comment by corydolphin** [comment]
Hey there @barelyknown,

It looks like Github changed their domains for serving user content, so the buildpack required a quick tweak (https://github.com/wcdolphin/heroku-buildpack-apache/commit/362cc7bfa3578305d4a6e3362fa75fb30a56cbe9)

If you re-run `hbench create`, you should be all set to go!

Sorry for the trouble, and please let me know if you find this project useful :-)

Cory

**Comment by barelyknown** [comment]
Great. Works perfect now.

I wanted to measure latency between applications hosted on Heroku, and this is perfect for that.
